# -*- coding: utf-8 -*-
"""Weather data sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P5E2a49y3u-_PufzxqD116ap32PhOBgb
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

weather_data = pd.read_csv(r'/content/weather_datasets - weather_data.csv')

weather_data.head()

weather_data.shape

weather_data.describe

weather_data.info()

weather_data['Date']=pd.to_datetime(weather_data['Date'])                              # converting date dtype from obj  to datetime

weather_data.set_index('Date',inplace=True)

weather_data.index.dtype

weather_data.info()

weather_data=weather_data.dropna()

weather_data.head(2)

weather_data.hist(bins=44,figsize=(22,16))                                               # Histogram ploting
plt.show()

corr_matrix=weather_data.corr()                                                            # shown heatmap using sns
plt.figure(figsize=(16,8))
sns.heatmap(corr_matrix,annot=True)
plt.show()

plt.figure(figsize=(13,7))
sns.lineplot(x="Average temperature (°F)",y="Average windspeed (mph)",data=weather_data)                          # Average temp Vs Average windspeed line plot is shown
plt.show()

plt.figure(figsize=(12,7))
sns.lineplot(x="Average direction (°deg)", y="Maximum wind speed (mph)", data=weather_data)
plt.xlabel("Average direction (°deg)")
plt.ylabel("Maximum wind speed (mph)")
plt.title("Line Plot of Maximum Wind Speed vs Average Direction")
plt.show()

# count of the minimum number of days for the time when temperature reduced

weather_data.sort_values(by="Date", inplace=True)                             #Sort data by date

weather_data["temp_diff"] = weather_data["Maximum temperature (°F)"].diff()               #difference in temperature between consecutive days

count = (weather_data["temp_diff"] < 0).sum()                             #number of days when the difference in temperature is negative

print("The minimum no days when temperature reduced :", count)















